// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sms/sms.proto

package sms

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//email发送验证码
type SendEmailCodeRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailCodeRequest) Reset()         { *m = SendEmailCodeRequest{} }
func (m *SendEmailCodeRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailCodeRequest) ProtoMessage()    {}
func (*SendEmailCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{0}
}

func (m *SendEmailCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailCodeRequest.Unmarshal(m, b)
}
func (m *SendEmailCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailCodeRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailCodeRequest.Merge(m, src)
}
func (m *SendEmailCodeRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailCodeRequest.Size(m)
}
func (m *SendEmailCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailCodeRequest proto.InternalMessageInfo

func (m *SendEmailCodeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

//发送结果
type SendResultResponse struct {
	Errcode              int64    `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResultResponse) Reset()         { *m = SendResultResponse{} }
func (m *SendResultResponse) String() string { return proto.CompactTextString(m) }
func (*SendResultResponse) ProtoMessage()    {}
func (*SendResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{1}
}

func (m *SendResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResultResponse.Unmarshal(m, b)
}
func (m *SendResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResultResponse.Marshal(b, m, deterministic)
}
func (m *SendResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResultResponse.Merge(m, src)
}
func (m *SendResultResponse) XXX_Size() int {
	return xxx_messageInfo_SendResultResponse.Size(m)
}
func (m *SendResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResultResponse proto.InternalMessageInfo

func (m *SendResultResponse) GetErrcode() int64 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *SendResultResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//验证码校验请求
type ValidateCodeRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	PublishMode          string   `protobuf:"bytes,3,opt,name=publish_mode,json=publishMode,proto3" json:"publish_mode,omitempty"`
	PublishType          string   `protobuf:"bytes,4,opt,name=publish_type,json=publishType,proto3" json:"publish_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateCodeRequest) Reset()         { *m = ValidateCodeRequest{} }
func (m *ValidateCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateCodeRequest) ProtoMessage()    {}
func (*ValidateCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{2}
}

func (m *ValidateCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateCodeRequest.Unmarshal(m, b)
}
func (m *ValidateCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateCodeRequest.Marshal(b, m, deterministic)
}
func (m *ValidateCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateCodeRequest.Merge(m, src)
}
func (m *ValidateCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateCodeRequest.Size(m)
}
func (m *ValidateCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateCodeRequest proto.InternalMessageInfo

func (m *ValidateCodeRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ValidateCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ValidateCodeRequest) GetPublishMode() string {
	if m != nil {
		return m.PublishMode
	}
	return ""
}

func (m *ValidateCodeRequest) GetPublishType() string {
	if m != nil {
		return m.PublishType
	}
	return ""
}

//验证码校验响应
type ValidateCodeResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateCodeResponse) Reset()         { *m = ValidateCodeResponse{} }
func (m *ValidateCodeResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateCodeResponse) ProtoMessage()    {}
func (*ValidateCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{3}
}

func (m *ValidateCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateCodeResponse.Unmarshal(m, b)
}
func (m *ValidateCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateCodeResponse.Marshal(b, m, deterministic)
}
func (m *ValidateCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateCodeResponse.Merge(m, src)
}
func (m *ValidateCodeResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateCodeResponse.Size(m)
}
func (m *ValidateCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateCodeResponse proto.InternalMessageInfo

func (m *ValidateCodeResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*SendEmailCodeRequest)(nil), "sms.SendEmailCodeRequest")
	proto.RegisterType((*SendResultResponse)(nil), "sms.SendResultResponse")
	proto.RegisterType((*ValidateCodeRequest)(nil), "sms.ValidateCodeRequest")
	proto.RegisterType((*ValidateCodeResponse)(nil), "sms.ValidateCodeResponse")
}

func init() { proto.RegisterFile("proto/sms/sms.proto", fileDescriptor_ab867e236c3ccf27) }

var fileDescriptor_ab867e236c3ccf27 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x41, 0x4f, 0xb3, 0x40,
	0x10, 0xfd, 0xf8, 0xa8, 0xa8, 0x63, 0x4d, 0xcc, 0x94, 0x54, 0xda, 0x93, 0x72, 0xf2, 0x60, 0x30,
	0xd1, 0x9f, 0x60, 0xf0, 0xe6, 0x65, 0x6b, 0xbc, 0x1a, 0x2a, 0x13, 0x25, 0xb2, 0x05, 0x77, 0x96,
	0x03, 0x47, 0x7f, 0x83, 0x7f, 0xd8, 0xec, 0x74, 0x6b, 0x8a, 0xe1, 0x40, 0x32, 0x6f, 0xde, 0x63,
	0xde, 0xcc, 0x5b, 0x98, 0xb5, 0xa6, 0xb1, 0xcd, 0x0d, 0x6b, 0x76, 0x5f, 0x26, 0x08, 0x43, 0xd6,
	0x9c, 0x5e, 0x43, 0xbc, 0xa2, 0x4d, 0x99, 0xeb, 0xa2, 0xaa, 0xef, 0x9b, 0x92, 0x14, 0x7d, 0x76,
	0xc4, 0x16, 0x63, 0x38, 0x20, 0xd7, 0x4b, 0x82, 0x8b, 0xe0, 0xea, 0x58, 0x6d, 0x41, 0xfa, 0x00,
	0xe8, 0xd4, 0x8a, 0xb8, 0xab, 0xad, 0x22, 0x6e, 0x9b, 0x0d, 0x13, 0x26, 0x70, 0x48, 0xc6, 0xbc,
	0x36, 0x25, 0x89, 0x3a, 0x54, 0x3b, 0x88, 0x73, 0x88, 0xc8, 0x18, 0xcd, 0x6f, 0xc9, 0x7f, 0x19,
	0xe3, 0x51, 0xfa, 0x15, 0xc0, 0xec, 0xb9, 0xa8, 0xab, 0xb2, 0xb0, 0xb4, 0xef, 0x7a, 0x06, 0xe1,
	0x07, 0xf5, 0xde, 0xd3, 0x95, 0x88, 0x30, 0x91, 0xc1, 0xdb, 0xff, 0xa5, 0xc6, 0x4b, 0x98, 0xb6,
	0xdd, 0xba, 0xae, 0xf8, 0xfd, 0x45, 0x3b, 0x2e, 0x14, 0xee, 0xc4, 0xf7, 0x1e, 0xff, 0x48, 0x6c,
	0xdf, 0x52, 0x32, 0x19, 0x48, 0x9e, 0xfa, 0x96, 0xd2, 0x0c, 0xe2, 0xe1, 0x0a, 0xfe, 0x9a, 0x39,
	0x44, 0x46, 0xee, 0x93, 0x35, 0x8e, 0x94, 0x47, 0xb7, 0xdf, 0x01, 0x84, 0x2b, 0xcd, 0x98, 0xc3,
	0xe9, 0x20, 0x31, 0x5c, 0x64, 0x2e, 0xd3, 0xb1, 0x14, 0x97, 0xe7, 0xbf, 0xd4, 0x30, 0xb2, 0xf4,
	0x1f, 0xe6, 0x30, 0xdd, 0xb7, 0xc7, 0x44, 0xa4, 0x23, 0xa1, 0x2c, 0x17, 0x23, 0xcc, 0x6e, 0xcc,
	0x3a, 0x92, 0xb7, 0xbc, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x48, 0x08, 0x31, 0x24, 0xe2, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmsClient is the client API for Sms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmsClient interface {
	//email发送验证码
	SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendResultResponse, error)
	//验证码校验
	ValidateCode(ctx context.Context, in *ValidateCodeRequest, opts ...grpc.CallOption) (*ValidateCodeResponse, error)
}

type smsClient struct {
	cc *grpc.ClientConn
}

func NewSmsClient(cc *grpc.ClientConn) SmsClient {
	return &smsClient{cc}
}

func (c *smsClient) SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendResultResponse, error) {
	out := new(SendResultResponse)
	err := c.cc.Invoke(ctx, "/sms.Sms/SendEmailCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) ValidateCode(ctx context.Context, in *ValidateCodeRequest, opts ...grpc.CallOption) (*ValidateCodeResponse, error) {
	out := new(ValidateCodeResponse)
	err := c.cc.Invoke(ctx, "/sms.Sms/ValidateCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServer is the server API for Sms service.
type SmsServer interface {
	//email发送验证码
	SendEmailCode(context.Context, *SendEmailCodeRequest) (*SendResultResponse, error)
	//验证码校验
	ValidateCode(context.Context, *ValidateCodeRequest) (*ValidateCodeResponse, error)
}

// UnimplementedSmsServer can be embedded to have forward compatible implementations.
type UnimplementedSmsServer struct {
}

func (*UnimplementedSmsServer) SendEmailCode(ctx context.Context, req *SendEmailCodeRequest) (*SendResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailCode not implemented")
}
func (*UnimplementedSmsServer) ValidateCode(ctx context.Context, req *ValidateCodeRequest) (*ValidateCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCode not implemented")
}

func RegisterSmsServer(s *grpc.Server, srv SmsServer) {
	s.RegisterService(&_Sms_serviceDesc, srv)
}

func _Sms_SendEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).SendEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.Sms/SendEmailCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).SendEmailCode(ctx, req.(*SendEmailCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_ValidateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).ValidateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.Sms/ValidateCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).ValidateCode(ctx, req.(*ValidateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sms.Sms",
	HandlerType: (*SmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmailCode",
			Handler:    _Sms_SendEmailCode_Handler,
		},
		{
			MethodName: "ValidateCode",
			Handler:    _Sms_ValidateCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sms/sms.proto",
}
