// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sms/sms.proto

package sms

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//email发送验证码
type SendEmailCodeRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailCodeRequest) Reset()         { *m = SendEmailCodeRequest{} }
func (m *SendEmailCodeRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailCodeRequest) ProtoMessage()    {}
func (*SendEmailCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{0}
}

func (m *SendEmailCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailCodeRequest.Unmarshal(m, b)
}
func (m *SendEmailCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailCodeRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailCodeRequest.Merge(m, src)
}
func (m *SendEmailCodeRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailCodeRequest.Size(m)
}
func (m *SendEmailCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailCodeRequest proto.InternalMessageInfo

func (m *SendEmailCodeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

//发送结果
type SendResultResponse struct {
	Errcode              int64    `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResultResponse) Reset()         { *m = SendResultResponse{} }
func (m *SendResultResponse) String() string { return proto.CompactTextString(m) }
func (*SendResultResponse) ProtoMessage()    {}
func (*SendResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab867e236c3ccf27, []int{1}
}

func (m *SendResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResultResponse.Unmarshal(m, b)
}
func (m *SendResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResultResponse.Marshal(b, m, deterministic)
}
func (m *SendResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResultResponse.Merge(m, src)
}
func (m *SendResultResponse) XXX_Size() int {
	return xxx_messageInfo_SendResultResponse.Size(m)
}
func (m *SendResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResultResponse proto.InternalMessageInfo

func (m *SendResultResponse) GetErrcode() int64 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *SendResultResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*SendEmailCodeRequest)(nil), "sms.SendEmailCodeRequest")
	proto.RegisterType((*SendResultResponse)(nil), "sms.SendResultResponse")
}

func init() { proto.RegisterFile("proto/sms/sms.proto", fileDescriptor_ab867e236c3ccf27) }

var fileDescriptor_ab867e236c3ccf27 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x2d, 0x06, 0x61, 0x3d, 0x30, 0x4f, 0x88, 0xb9, 0x38, 0xb7, 0x58, 0x49,
	0x87, 0x4b, 0x24, 0x38, 0x35, 0x2f, 0xc5, 0x35, 0x37, 0x31, 0x33, 0xc7, 0x39, 0x3f, 0x25, 0x35,
	0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x84, 0x8b, 0x35, 0x15, 0x24, 0x26, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x28, 0xb9, 0x71, 0x09, 0x81, 0x54, 0x07, 0xa5, 0x16, 0x97,
	0xe6, 0x94, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x49, 0x70, 0xb1, 0xa7, 0x16,
	0x15, 0x25, 0xe7, 0xa7, 0xa4, 0x82, 0x55, 0x33, 0x07, 0xc1, 0xb8, 0x42, 0x62, 0x5c, 0x6c, 0xa9,
	0x45, 0x45, 0xb9, 0xc5, 0xe9, 0x12, 0x4c, 0x60, 0x63, 0xa0, 0x3c, 0x23, 0x1f, 0x2e, 0xe6, 0xe0,
	0xdc, 0x62, 0x21, 0x57, 0x2e, 0x5e, 0x14, 0xcb, 0x85, 0x24, 0xf5, 0x40, 0xce, 0xc3, 0xe6, 0x20,
	0x29, 0x71, 0xb8, 0x14, 0xaa, 0xed, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xff, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0x15, 0x31, 0xc4, 0xe6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmsClient is the client API for Sms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmsClient interface {
	//email发送验证码
	SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendResultResponse, error)
}

type smsClient struct {
	cc *grpc.ClientConn
}

func NewSmsClient(cc *grpc.ClientConn) SmsClient {
	return &smsClient{cc}
}

func (c *smsClient) SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendResultResponse, error) {
	out := new(SendResultResponse)
	err := c.cc.Invoke(ctx, "/sms.Sms/SendEmailCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServer is the server API for Sms service.
type SmsServer interface {
	//email发送验证码
	SendEmailCode(context.Context, *SendEmailCodeRequest) (*SendResultResponse, error)
}

// UnimplementedSmsServer can be embedded to have forward compatible implementations.
type UnimplementedSmsServer struct {
}

func (*UnimplementedSmsServer) SendEmailCode(ctx context.Context, req *SendEmailCodeRequest) (*SendResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailCode not implemented")
}

func RegisterSmsServer(s *grpc.Server, srv SmsServer) {
	s.RegisterService(&_Sms_serviceDesc, srv)
}

func _Sms_SendEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).SendEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.Sms/SendEmailCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).SendEmailCode(ctx, req.(*SendEmailCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sms.Sms",
	HandlerType: (*SmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmailCode",
			Handler:    _Sms_SendEmailCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sms/sms.proto",
}
